apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guessme

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: guessme
  managed-by: kustomize
