apiVersion: ray.io/v1
kind: RayService
metadata:
  name: guessme
  namespace: guessme
spec:
  serveConfigV2: |
    applications:
      - name: guessme
        import_path: guessme.main:app
        route_prefix: /
        deployments:
          - name: GuessmeApp
            num_replicas: 1
            ray_actor_options:
              num_cpus: 0.5

  rayClusterConfig:
    rayVersion: '2.41.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
            - name: ray-head
              image: guessme-backend
              ports:
                - containerPort: 6379
                  name: gcs
                - containerPort: 8265
                  name: dashboard
                - containerPort: 8000
                  name: serve
              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
              env:
                - name: RAY_SERVE_ENABLE_EXPERIMENTAL_STREAMING
                  value: "1"
                - name: PYTHONPATH
                  value: "/app/src"
                - name: PATH
                  value: "/app/.venv/bin:/usr/local/bin:/usr/bin:/bin"
